# Copyright (C) 2024 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only

# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb \
            ${LAYERDIR}/recipes*/*/*.bbappend \
            "
BBFILE_COLLECTIONS += "b2qt"
BBFILE_PATTERN_b2qt := "^${LAYERDIR}/"
BBFILE_PRIORITY_b2qt = "20"

LICENSE_PATH += "${LAYERDIR}/licenses"
BOOT2QTBASE = "${LAYERDIR}"
BB_BASEHASH_IGNORE_VARS:append = " BOOT2QTBASE"

HOSTTOOLS += "git-lfs"

LAYERSERIES_COMPAT_b2qt = "kirkstone langdale mickledore nanbield scarthgap"
