# Copyright (C) 2024 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only

include conf/distro/poky.conf

DISTRO = "b2qt"
DISTRO_NAME = "Boot to Qt for Embedded Linux"
SDK_VERSION := "${DISTRO_VERSION}"

BUILDCFG_VARS += "SDKMACHINE QT_VERSION"

MACHINE_HOSTNAME ?= "b2qt-${MACHINE}"

MAINTAINER = "B2Qt <b2qt@qt.io>"

SYSVINIT_ENABLED_GETTYS = ""

POKY_DEFAULT_DISTRO_FEATURES:remove = "ptest"
DISTRO_FEATURES_DEFAULT:remove = "irda pcmcia pci 3g nfc zeroconf x11"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"

DISTRO_FEATURES_FILTER_NATIVESDK:append = " wayland"

FONTCONFIG_CACHE_DIR = "${libdir}/fontconfig/cache"

DISTRO_FEATURES += "gstreamer webengine systemd pam virtualization minidebuginfo"
DISTRO_FEATURES:remove:mipsarch = "webengine virtualization"
DISTRO_FEATURES:remove:riscv64 = "webengine virtualization"

INIT_MANAGER = "systemd"

PREFERRED_PROVIDER_jpeg ?= "libjpeg-turbo"
PREFERRED_PROVIDER_jpeg-native ?= "libjpeg-turbo-native"

IMAGE_FSTYPES += "conf"
IMAGE_CLASSES += "deploy-conf"

QBSP_README ?= "README"
QBSP_IMAGE_CONTENT ?= "${QBSP_README}"
QBSP_IMAGE_DEPENDS ?= "qbsp-readme:do_deploy"

LICENSE_CREATE_PACKAGE = "1"
COPY_LIC_MANIFEST = "1"

CLANG_EXTRA_OE_VENDORS = "${TARGET_VENDOR} -pokysdk"

QT_EDITION = "commercial"

USE_SQUISH ?= "${@bb.utils.contains('QT_INTERNAL_BUILD', '1', \
    bb.utils.vercmp_string_op(d.getVar('QT_VERSION'), '6.6', '>') & \
    bb.utils.vercmp_string_op(d.getVar('QT_VERSION'), '6.9', '<'), False, d)}"
USE_SQUISH:mipsarch ?= "0"

include conf/distro/include/b2qt.inc
include conf/distro/include/machine-settings.inc
include conf/distro/include/preferred-providers-${SDK_OS}.inc

inherit core-image-selinux
