# Copyright (C) 2024 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only

# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb \
            ${LAYERDIR}/recipes*/*/*.bbappend \
            "

BBFILE_COLLECTIONS += "b2qt-distro"
BBFILE_PATTERN_b2qt-distro := "^${LAYERDIR}/"
BBFILE_PRIORITY_b2qt-distro = "20"

LAYERSERIES_COMPAT_b2qt-distro = "scarthgap"

# recipe appends for machine specific BSP layers
BBFILES_DYNAMIC += " \
    freescale-layer:${LAYERDIR}/dynamic-layers/freescale-layer/recipes*/*/*.bb \
    freescale-layer:${LAYERDIR}/dynamic-layers/freescale-layer/recipes*/*/*.bbappend \
    intel:${LAYERDIR}/dynamic-layers/intel/recipes*/*/*.bb \
    intel:${LAYERDIR}/dynamic-layers/intel/recipes*/*/*.bbappend \
    raspberrypi:${LAYERDIR}/dynamic-layers/raspberrypi/recipes*/*/*.bb \
    raspberrypi:${LAYERDIR}/dynamic-layers/raspberrypi/recipes*/*/*.bbappend \
    tegra:${LAYERDIR}/dynamic-layers/tegra/recipes*/*/*.bb \
    tegra:${LAYERDIR}/dynamic-layers/tegra/recipes*/*/*.bbappend \
"

BBMASK += "${@ 'qtspeech_git.bbappend' if bb.utils.vercmp_string(d.getVar('QT_VERSION'), '6.4') < 0 else '' }"
BBMASK += "${@ 'qtvncserver_git.bbappend' if bb.utils.vercmp_string(d.getVar('QT_VERSION'), '6.5') < 0 else '' }"
